<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net6.0-windows;net8.0-windows</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseWpf>true</UseWpf>
    <NoWarn>$(NoWarn);PInvoke009;CA1806</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Snoop.InjectorLauncher\InjectorLauncherCommandLineOptions.cs" Link="InjectorLauncherCommandLineOptions.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Snoop.Core/Snoop.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
  </ItemGroup>
</Project>
