// <auto-generated/>
// Polyfills required for C# 9+ and C# 11 features on .NET Framework 4.6.2 / .NET 6.
// These are compiler-only types; no runtime dependency is introduced.
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1502 // Element should not be on a single line
#pragma warning disable SA1516 // Elements should be separated by blank line
#pragma warning disable SA1101 // Prefix local calls with this

#if !NET5_0_OR_GREATER
namespace System.Runtime.CompilerServices
{
    using System.ComponentModel;

    /// <summary>Enables the <c>init</c> accessor and <c>record</c> types on .NET Framework.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal static class IsExternalInit
    {
    }
}
#endif

#if !NET7_0_OR_GREATER
namespace System.Runtime.CompilerServices
{
    using System.ComponentModel;

    /// <summary>Enables the C# 11 <c>required</c> modifier on older TFMs.</summary>
    [AttributeUsage(
        AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Field | AttributeTargets.Property,
        AllowMultiple = false,
        Inherited = false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal sealed class RequiredMemberAttribute : Attribute
    {
    }

    /// <summary>Compiler-required companion for <see cref="RequiredMemberAttribute"/>.</summary>
    [AttributeUsage(AttributeTargets.All, AllowMultiple = true, Inherited = false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal sealed class CompilerFeatureRequiredAttribute : Attribute
    {
        /// <summary>Initialises a new instance.</summary>
        public CompilerFeatureRequiredAttribute(string featureName)
        {
            this.FeatureName = featureName;
        }

        /// <summary>Gets the feature name.</summary>
        public string FeatureName { get; }

        /// <summary>Gets or sets a value indicating whether the feature is optional.</summary>
        public bool IsOptional { get; init; }
    }
}

namespace System.Diagnostics.CodeAnalysis
{
    using System.ComponentModel;

    /// <summary>Enables the C# 11 <c>required</c> modifier on older TFMs.</summary>
    [AttributeUsage(AttributeTargets.Constructor, AllowMultiple = false, Inherited = false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal sealed class SetsRequiredMembersAttribute : Attribute
    {
    }
}
#endif
